// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: proto/RicartAgrawalaService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerbotenZoneMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *VerbotenZoneMsg) Reset() {
	*x = VerbotenZoneMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RicartAgrawalaService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerbotenZoneMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerbotenZoneMsg) ProtoMessage() {}

func (x *VerbotenZoneMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RicartAgrawalaService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerbotenZoneMsg.ProtoReflect.Descriptor instead.
func (*VerbotenZoneMsg) Descriptor() ([]byte, []int) {
	return file_proto_RicartAgrawalaService_proto_rawDescGZIP(), []int{0}
}

func (x *VerbotenZoneMsg) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RequestMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId      int32  `protobuf:"varint,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	LPTimestamp int32  `protobuf:"varint,2,opt,name=LPTimestamp,proto3" json:"LPTimestamp,omitempty"`
	Addr        string `protobuf:"bytes,3,opt,name=Addr,proto3" json:"Addr,omitempty"`
}

func (x *RequestMsg) Reset() {
	*x = RequestMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RicartAgrawalaService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMsg) ProtoMessage() {}

func (x *RequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RicartAgrawalaService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMsg.ProtoReflect.Descriptor instead.
func (*RequestMsg) Descriptor() ([]byte, []int) {
	return file_proto_RicartAgrawalaService_proto_rawDescGZIP(), []int{1}
}

func (x *RequestMsg) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RequestMsg) GetLPTimestamp() int32 {
	if x != nil {
		return x.LPTimestamp
	}
	return 0
}

func (x *RequestMsg) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ResponseMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId      int32 `protobuf:"varint,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	LPTimestamp int32 `protobuf:"varint,2,opt,name=LPTimestamp,proto3" json:"LPTimestamp,omitempty"`
}

func (x *ResponseMsg) Reset() {
	*x = ResponseMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RicartAgrawalaService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMsg) ProtoMessage() {}

func (x *ResponseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RicartAgrawalaService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMsg.ProtoReflect.Descriptor instead.
func (*ResponseMsg) Descriptor() ([]byte, []int) {
	return file_proto_RicartAgrawalaService_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseMsg) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ResponseMsg) GetLPTimestamp() int32 {
	if x != nil {
		return x.LPTimestamp
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_RicartAgrawalaService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RicartAgrawalaService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_RicartAgrawalaService_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_RicartAgrawalaService_proto protoreflect.FileDescriptor

var file_proto_RicartAgrawalaService_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x52, 0x69, 0x63, 0x61, 0x72, 0x74, 0x41, 0x67,
	0x72, 0x61, 0x77, 0x61, 0x6c, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0f, 0x56, 0x65,
	0x72, 0x62, 0x6f, 0x74, 0x65, 0x6e, 0x5a, 0x6f, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x5a, 0x0a,
	0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x50, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x4c, 0x50, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x22, 0x47, 0x0a, 0x0b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x50, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x4c, 0x50, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x1d, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x32, 0x71, 0x0a, 0x15, 0x52, 0x69, 0x63, 0x61, 0x72, 0x74, 0x41, 0x67, 0x72, 0x61, 0x77,
	0x61, 0x6c, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x1a, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x63, 0x6b, 0x22, 0x00, 0x32, 0x72, 0x0a, 0x13, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x74, 0x65, 0x6e,
	0x5a, 0x6f, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x47,
	0x6f, 0x49, 0x6e, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x62,
	0x6f, 0x74, 0x65, 0x6e, 0x5a, 0x6f, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x1a, 0x0a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x05, 0x47, 0x6f, 0x4f,
	0x75, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x62, 0x6f,
	0x74, 0x65, 0x6e, 0x5a, 0x6f, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x1a, 0x0a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x32, 0x70, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_RicartAgrawalaService_proto_rawDescOnce sync.Once
	file_proto_RicartAgrawalaService_proto_rawDescData = file_proto_RicartAgrawalaService_proto_rawDesc
)

func file_proto_RicartAgrawalaService_proto_rawDescGZIP() []byte {
	file_proto_RicartAgrawalaService_proto_rawDescOnce.Do(func() {
		file_proto_RicartAgrawalaService_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_RicartAgrawalaService_proto_rawDescData)
	})
	return file_proto_RicartAgrawalaService_proto_rawDescData
}

var file_proto_RicartAgrawalaService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_RicartAgrawalaService_proto_goTypes = []interface{}{
	(*VerbotenZoneMsg)(nil), // 0: proto.VerbotenZoneMsg
	(*RequestMsg)(nil),      // 1: proto.RequestMsg
	(*ResponseMsg)(nil),     // 2: proto.ResponseMsg
	(*Ack)(nil),             // 3: proto.Ack
}
var file_proto_RicartAgrawalaService_proto_depIdxs = []int32{
	1, // 0: proto.RicartAgrawalaService.Request:input_type -> proto.RequestMsg
	2, // 1: proto.RicartAgrawalaService.Response:input_type -> proto.ResponseMsg
	0, // 2: proto.VerbotenZoneService.GoIn:input_type -> proto.VerbotenZoneMsg
	0, // 3: proto.VerbotenZoneService.GoOut:input_type -> proto.VerbotenZoneMsg
	3, // 4: proto.RicartAgrawalaService.Request:output_type -> proto.Ack
	3, // 5: proto.RicartAgrawalaService.Response:output_type -> proto.Ack
	3, // 6: proto.VerbotenZoneService.GoIn:output_type -> proto.Ack
	3, // 7: proto.VerbotenZoneService.GoOut:output_type -> proto.Ack
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_RicartAgrawalaService_proto_init() }
func file_proto_RicartAgrawalaService_proto_init() {
	if File_proto_RicartAgrawalaService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_RicartAgrawalaService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerbotenZoneMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RicartAgrawalaService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RicartAgrawalaService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_RicartAgrawalaService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_RicartAgrawalaService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_RicartAgrawalaService_proto_goTypes,
		DependencyIndexes: file_proto_RicartAgrawalaService_proto_depIdxs,
		MessageInfos:      file_proto_RicartAgrawalaService_proto_msgTypes,
	}.Build()
	File_proto_RicartAgrawalaService_proto = out.File
	file_proto_RicartAgrawalaService_proto_rawDesc = nil
	file_proto_RicartAgrawalaService_proto_goTypes = nil
	file_proto_RicartAgrawalaService_proto_depIdxs = nil
}
