// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: proto/TokenRingService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerbotenZoneMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *VerbotenZoneMsg) Reset() {
	*x = VerbotenZoneMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TokenRingService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerbotenZoneMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerbotenZoneMsg) ProtoMessage() {}

func (x *VerbotenZoneMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TokenRingService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerbotenZoneMsg.ProtoReflect.Descriptor instead.
func (*VerbotenZoneMsg) Descriptor() ([]byte, []int) {
	return file_proto_TokenRingService_proto_rawDescGZIP(), []int{0}
}

func (x *VerbotenZoneMsg) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token bool `protobuf:"varint,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TokenRingService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TokenRingService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_proto_TokenRingService_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetToken() bool {
	if x != nil {
		return x.Token
	}
	return false
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TokenRingService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TokenRingService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_TokenRingService_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_TokenRingService_proto protoreflect.FileDescriptor

var file_proto_TokenRingService_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x69, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x74, 0x65,
	0x6e, 0x5a, 0x6f, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x1d, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x1d, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x3b, 0x0a, 0x10, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x09, 0x47, 0x69,
	0x76, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63,
	0x6b, 0x22, 0x00, 0x32, 0x72, 0x0a, 0x13, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x74, 0x65, 0x6e, 0x5a,
	0x6f, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x47, 0x6f,
	0x49, 0x6e, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x62, 0x6f,
	0x74, 0x65, 0x6e, 0x5a, 0x6f, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x1a, 0x0a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x05, 0x47, 0x6f, 0x4f, 0x75,
	0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x74,
	0x65, 0x6e, 0x5a, 0x6f, 0x6e, 0x65, 0x4d, 0x73, 0x67, 0x1a, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x63, 0x6b, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x32, 0x70, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_TokenRingService_proto_rawDescOnce sync.Once
	file_proto_TokenRingService_proto_rawDescData = file_proto_TokenRingService_proto_rawDesc
)

func file_proto_TokenRingService_proto_rawDescGZIP() []byte {
	file_proto_TokenRingService_proto_rawDescOnce.Do(func() {
		file_proto_TokenRingService_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_TokenRingService_proto_rawDescData)
	})
	return file_proto_TokenRingService_proto_rawDescData
}

var file_proto_TokenRingService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_TokenRingService_proto_goTypes = []interface{}{
	(*VerbotenZoneMsg)(nil), // 0: proto.VerbotenZoneMsg
	(*Token)(nil),           // 1: proto.Token
	(*Ack)(nil),             // 2: proto.Ack
}
var file_proto_TokenRingService_proto_depIdxs = []int32{
	1, // 0: proto.TokenRingService.GiveToken:input_type -> proto.Token
	0, // 1: proto.VerbotenZoneService.GoIn:input_type -> proto.VerbotenZoneMsg
	0, // 2: proto.VerbotenZoneService.GoOut:input_type -> proto.VerbotenZoneMsg
	2, // 3: proto.TokenRingService.GiveToken:output_type -> proto.Ack
	2, // 4: proto.VerbotenZoneService.GoIn:output_type -> proto.Ack
	2, // 5: proto.VerbotenZoneService.GoOut:output_type -> proto.Ack
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_TokenRingService_proto_init() }
func file_proto_TokenRingService_proto_init() {
	if File_proto_TokenRingService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_TokenRingService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerbotenZoneMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TokenRingService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TokenRingService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_TokenRingService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_TokenRingService_proto_goTypes,
		DependencyIndexes: file_proto_TokenRingService_proto_depIdxs,
		MessageInfos:      file_proto_TokenRingService_proto_msgTypes,
	}.Build()
	File_proto_TokenRingService_proto = out.File
	file_proto_TokenRingService_proto_rawDesc = nil
	file_proto_TokenRingService_proto_goTypes = nil
	file_proto_TokenRingService_proto_depIdxs = nil
}
